import { GameCategory } from "@/hooks/useGameData";
import { IHint } from "@/hooks/useManageHints";

export const defaultHints: Record<GameCategory, IHint[]> = {
  famousPerson: [
    { id: 1, hint: "This person is known for their contributions to science.", isUsed: false },
    { id: 2, hint: "They won a Nobel Prize in Physics.", isUsed: false },
    { id: 3, hint: "They developed the theory of relativity.", isUsed: false },
    { id: 4, hint: "They were born in Germany.", isUsed: false },
    { id: 5, hint: "Their name is associated with the equation E=mc².", isUsed: false },
    { id: 6, hint: "They worked on quantum mechanics.", isUsed: false },
    { id: 7, hint: "They were a professor at Princeton University.", isUsed: false },
    { id: 8, hint: "They had a famous hairstyle.", isUsed: false },
    { id: 9, hint: "They were awarded the Copley Medal.", isUsed: false },
    { id: 10, hint: "They were a pacifist.", isUsed: false },
    { id: 11, hint: "They emigrated to the United States.", isUsed: false },
    { id: 12, hint: "They were born in the 19th century.", isUsed: false },
    { id: 13, hint: "They were a theoretical physicist.", isUsed: false },
    { id: 14, hint: "They were a violinist.", isUsed: false },
    { id: 15, hint: "They were a member of the Academy of Sciences.", isUsed: false },
    { id: 16, hint: "They were a vegetarian.", isUsed: false },
    { id: 17, hint: "They were known for their humanitarian efforts.", isUsed: false },
    { id: 18, hint: "They were married twice.", isUsed: false },
    { id: 19, hint: "They were a patent clerk.", isUsed: false },
    { id: 20, hint: "They passed away in 1955.", isUsed: false },
  ],
  word: [
    { id: 1, hint: "This word is often used to describe something that is very large.", isUsed: false },
    { id: 2, hint: "It can also mean 'impressive' or 'extraordinary'.", isUsed: false },
    { id: 3, hint: "It starts with the letter 'G'.", isUsed: false },
    { id: 4, hint: "It is often used in the context of achievements.", isUsed: false },
    { id: 5, hint: "It rhymes with 'fantastic'.", isUsed: false },
    { id: 6, hint: "It is a synonym for 'immense'.", isUsed: false },
    { id: 7, hint: "It is used to describe size or scale.", isUsed: false },
    { id: 8, hint: "It is a positive adjective.", isUsed: false },
    { id: 9, hint: "It is often used in storytelling.", isUsed: false },
    { id: 10, hint: "It is a common word in English.", isUsed: false },
    { id: 11, hint: "It is used in advertising slogans.", isUsed: false },
    { id: 12, hint: "It is a word with seven letters.", isUsed: false },
    { id: 13, hint: "It is used to describe events.", isUsed: false },
    { id: 14, hint: "It is used in speeches.", isUsed: false },
    { id: 15, hint: "It is used to describe landscapes.", isUsed: false },
    { id: 16, hint: "It is used to describe emotions.", isUsed: false },
    { id: 17, hint: "It is used to describe buildings.", isUsed: false },
    { id: 18, hint: "It is used to describe ideas.", isUsed: false },
    { id: 19, hint: "It is used to describe achievements.", isUsed: false },
    { id: 20, hint: "It is used to describe dreams.", isUsed: false },
  ],
  movie: [
    { id: 1, hint: "This movie was released in the early 2000s.", isUsed: false },
    { id: 2, hint: "It features a famous actor known for action films.", isUsed: false },
    { id: 3, hint: "It is set in a dystopian future.", isUsed: false },
    { id: 4, hint: "It has a famous soundtrack.", isUsed: false },
    { id: 5, hint: "It won several awards.", isUsed: false },
    { id: 6, hint: "It is part of a trilogy.", isUsed: false },
    { id: 7, hint: "It has a memorable villain.", isUsed: false },
    { id: 8, hint: "It was directed by a renowned filmmaker.", isUsed: false },
    { id: 9, hint: "It has groundbreaking visual effects.", isUsed: false },
    { id: 10, hint: "It is based on a book.", isUsed: false },
    { id: 11, hint: "It has a famous quote.", isUsed: false },
    { id: 12, hint: "It has a strong female lead.", isUsed: false },
    { id: 13, hint: "It is set in space.", isUsed: false },
    { id: 14, hint: "It has a twist ending.", isUsed: false },
    { id: 15, hint: "It is a science fiction film.", isUsed: false },
    { id: 16, hint: "It has a cult following.", isUsed: false },
    { id: 17, hint: "It has a famous fight scene.", isUsed: false },
    { id: 18, hint: "It has a memorable opening scene.", isUsed: false },
    { id: 19, hint: "It has a famous director cameo.", isUsed: false },
    { id: 20, hint: "It has a sequel.", isUsed: false },
  ],
  animal: [
    { id: 1, hint: "This animal is known for its long neck.", isUsed: false },
    { id: 2, hint: "It is often found in savannas and grasslands.", isUsed: false },
    { id: 3, hint: "It is a herbivore.", isUsed: false },
    { id: 4, hint: "It has distinctive spots.", isUsed: false },
    { id: 5, hint: "It is the tallest land animal.", isUsed: false },
    { id: 6, hint: "It has a prehensile tongue.", isUsed: false },
    { id: 7, hint: "It is native to Africa.", isUsed: false },
    { id: 8, hint: "It has long legs.", isUsed: false },
    { id: 9, hint: "It is a mammal.", isUsed: false },
    { id: 10, hint: "It has a gentle nature.", isUsed: false },
    { id: 11, hint: "It is often seen in zoos.", isUsed: false },
    { id: 12, hint: "It has a unique gait.", isUsed: false },
    { id: 13, hint: "It has a small head.", isUsed: false },
    { id: 14, hint: "It is a social animal.", isUsed: false },
    { id: 15, hint: "It has a long tail.", isUsed: false },
    { id: 16, hint: "It is a ruminant.", isUsed: false },
    { id: 17, hint: "It has large eyes.", isUsed: false },
    { id: 18, hint: "It has a long lifespan.", isUsed: false },
    { id: 19, hint: "It is a symbol of grace.", isUsed: false },
    { id: 20, hint: "It has a unique coat pattern.", isUsed: false },
  ],
  country: [
    { id: 1, hint: "This country is known for its pyramids.", isUsed: false },
    { id: 2, hint: "It has a rich history dating back thousands of years.", isUsed: false },
    { id: 3, hint: "It is located in North Africa.", isUsed: false },
    { id: 4, hint: "It has the Nile River.", isUsed: false },
    { id: 5, hint: "It is famous for its ancient civilization.", isUsed: false },
    { id: 6, hint: "It has a desert climate.", isUsed: false },
    { id: 7, hint: "It has a famous museum.", isUsed: false },
    { id: 8, hint: "It has a famous archaeological site.", isUsed: false },
    { id: 9, hint: "It has a famous capital city.", isUsed: false },
    { id: 10, hint: "It has a famous cuisine.", isUsed: false },
    { id: 11, hint: "It has a famous flag.", isUsed: false },
    { id: 12, hint: "It has a famous festival.", isUsed: false },
    { id: 13, hint: "It has a famous monument.", isUsed: false },
    { id: 14, hint: "It has a famous leader.", isUsed: false },
    { id: 15, hint: "It has a famous language.", isUsed: false },
    { id: 16, hint: "It has a famous religion.", isUsed: false },
    { id: 17, hint: "It has a famous currency.", isUsed: false },
    { id: 18, hint: "It has a famous industry.", isUsed: false },
    { id: 19, hint: "It has a famous export.", isUsed: false },
    { id: 20, hint: "It has a famous tourist attraction.", isUsed: false },
  ],
};
